apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance-api
  template:
    metadata:
      labels:
        app: insurance-api
    spec:
      containers:
      - name: insurance-api
        image: insurance-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis-service"
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-api-service
spec:
  selector:
    app: insurance-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000